GYMWebApp/Controllers/OlcumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMWebApp.DAL;
using GYMWebApp.Models;
using GYMWebApp.Repository;
using System.Data.Entity;
using System.Web.DynamicData.ModelProviders;

namespace GYMWebApp.Controllers
{
    public class OlcumController : BaseController
    {
        private MeasurementModel _mamodel = new MeasurementModel();
        private Olcum _olcum = new Olcum();
        private Sporcu _sp = new Sporcu();
        OlcumTipi _olctip = new OlcumTipi();

        public ActionResult Index()
        {
            return View(_mamodel.ListtAll());
        }

        public ActionResult Create()
        {
            List<SelectListItem> sporlis = new List<SelectListItem>();
            foreach (var item in db.Sporcu.ToList())
            {
                sporlis.Add(new SelectListItem { Text = item.Adi, Value = item.Id.ToString() });
            }

            ViewBag.SporcuListesi = sporlis;

            List<SelectListItem> olcumtipi = new List<SelectListItem>();
            foreach (var item in db.OlcumTipi.ToList())
            {
                olcumtipi.Add(new SelectListItem { Text = item.OlcumTipi1, Value = item.Id.ToString() });
            }

            ViewBag.OlcumTipiListesi = olcumtipi;
            return View(_olcum);
        }

        [HttpPost]
        public ActionResult Create(Olcum olcum)
        {

            olcum.OlcumTarihi = DateTime.Now;
            _mamodel.Create(olcum);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Olcum olcum)
        {

            _mamodel.DeleteIt(olcum);
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id = 0)
        {
            List<SelectListItem> sporlis = new List<SelectListItem>();
            foreach (var item in db.Sporcu.ToList())
            {
                sporlis.Add(new SelectListItem { Text = item.Adi, Value = item.Id.ToString() });
            }

            ViewBag.SporcuListesi = sporlis;

            List<SelectListItem> olcumtipi = new List<SelectListItem>();
            foreach (var item in db.OlcumTipi.ToList())
            {
                olcumtipi.Add(new SelectListItem { Text = item.OlcumTipi1, Value = item.Id.ToString() });
            }

            ViewBag.OlcumTipiListesi = olcumtipi;

            return View(db.Olcum.Find(id));
        }

        [HttpPost]
        public ActionResult Update(Olcum olcum)
        {
            olcum.OlcumTarihi = DateTime.Now;
            db.Entry(olcum).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ListToDate(DateTime? StrDate, DateTime? EnDate, FormCollection _fc)
        {
            var data = db.Olcum
                .Where(o => o.OlcumTarihi >= StrDate && o.OlcumTarihi < EnDate)
                .Select(o => new TariheGoreOlcumListele
                {
                    Adi = o.Sporcu.Adi,
                    Soyadi = o.Sporcu.Soyadi,
                    Tarih = o.OlcumTarihi.Value
                });
            return View(data);
        }

        public ActionResult ListToOlcum(string searchString)
        {
                var olcum = from x in db.Olcum
                    select x;
                if (!String.IsNullOrEmpty(searchString))
                {
                    olcum = olcum.Where(s => s.Id.Equals(searchString));
                }
                return View(olcum.ToList());
        }
    }
}

GYMWebApp/Views/Olcum/Create.cshtml
@model GYMWebApp.DAL.Olcum

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Olcum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SporcuId, "Sporcu Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SporcuId", new SelectList(ViewBag.SporcuListesi, "Value", "Text"), "Sporcu Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SporcuId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OlcumTipiId, "Olcum Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownList("OlcumTipiId", new SelectList(ViewBag.OlcumTipiListesi, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OlcumTipiId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OlcumDegeri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OlcumDegeri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OlcumDegeri, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.OlcumTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OlcumTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OlcumTarihi, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

GYMWebApp/Views/Olcum/Delete.cshtml
@model GYMWebApp.DAL.Olcum

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Sil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Olcum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OlcumDegeri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OlcumDegeri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OlcumTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OlcumTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OlcumTipi.OlcumTipi1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OlcumTipi.OlcumTipi1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sporcu.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sporcu.Adi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }
</div>

GYMWebApp/Views/Olcum/Index.cshtml
@model IEnumerable<GYMWebApp.DAL.Olcum>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main.cshtml";
}



<p>
    @using (Html.BeginForm("Index", "Olcum", FormMethod.Post))
    {
        <table>
            <tr>
                <td><h3>@Html.ActionLink("Sporcuya Yeni Ölçümler Ekle", "Create")</h3></td>
                <th>
                    @*@Html.TextBox("Id", new SelectList(ViewBag.Sporcular, "Value", "Text"), htmlAttributes: new { @class = "form-control" })*@
                </th>

            </tr>

        </table>

    }

</p>
<table class="table">
    <tr>
        <th>
            ADI


        </th>
        <th>
            SOYADI


        </th>
        <th>
            ÖLÇÜM TİPİ

        </th>
        <th>
            ÖLÇÜM DEĞERİ

        </th>
        <th>
            ÖLÇÜM TARİHİ

        </th>
        <th>İŞLEMLER</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sporcu.Adi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sporcu.Soyadi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OlcumTipi.OlcumTipi1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OlcumDegeri)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OlcumTarihi)
        </td>

        <td>
            <button type="button" class="bg-yellow">  @Html.ActionLink("Düzenle", "Update", new { id = item.Id }) </button>
            <button type="button" class="bg-red">@Html.ActionLink("Sil", "Delete", new { id = item.Id }) </button>
        </td>
    </tr>
}

</table>

GYMWebApp/Views/Olcum/ListToDate.cshtml
@model IEnumerable<GYMWebApp.Models.TariheGoreOlcumListele>
@{
    ViewBag.Title = "ListToDate";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Tarihe Göre Ölçüm Listeleme Sayfası</h2>

<hr/>

    @using (Html.BeginForm("ListToDate", "Olcum", FormMethod.Post))
    {
        <input type="date" name="StrDate" placeholder="Tarih seçiniz"/>
        <input type="date" name="EnDate"  placeholder="Tarih seçiniz"/>
        <input type="submit" value="Ara" />
        <hr/>
        <table class="table">
            <tr>
                <td>AD</td>
                <td>SOYAD</td>
                <td>Ölçüm Tarihi</td>
            </tr>

            @foreach (var olcum in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem=>olcum.Adi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem=>olcum.Soyadi)
                    </td>
                    <td>
                        @olcum.Tarih.ToString("dd/MM/yyyy")
                    </td>

                </tr>
            }

        </table>
    }

GYMWebApp/Views/Olcum/ListToOlcum.cshtml
@model IEnumerable<GYMWebApp.DAL.Olcum>
@{
    ViewBag.Title = "ListToOlcum";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>ListToOlcum</h2>

<div class="form-group">
    <table style="text-align:left; margin-bottom:10px;">
        <tr>
        <td>Item Code</td>
        <td>@Html.TextBox("SearchString")
        </td>
        <tr style="background-color:lightgray;">
            <td colspan="2"></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" class="btn btn-block btn-info"id="buttonsearch" value="Search" />
            </td>
        </tr>
        <tr>

        </tr>
        @foreach (var item in Model) {

            <tr>
                <td>@Html.DisplayFor(modelItem => item.OlcumDegeri)</td>
                <td style="text-align:right;">@Html.DisplayFor(modelItem => item.Sporcu.Adi)</td>
                <td style="text-align:right;">@Html.DisplayFor(modelItem => item.Sporcu.Soyadi)</td>
            </tr>
        }

    </table>
</div>

GYMWebApp/Views/Olcum/Update.cshtml
@model GYMWebApp.DAL.Olcum

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Güncelle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Olcum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SporcuId, "Sporcu Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SporcuId", new SelectList(ViewBag.SporcuListesi, "Value", "Text"), "Sporcu Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SporcuId, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.OlcumTipiId, "Olcum Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OlcumTipiId", new SelectList(ViewBag.OlcumTipiListesi, "Value", "Text"), "Ölçüm Tipi Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OlcumTipiId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OlcumDegeri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OlcumDegeri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OlcumDegeri, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.OlcumTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OlcumTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OlcumTarihi, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>