GYMWebApp/Controllers/AntremanController.cs
using GYMWebApp.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMWebApp.DAL;
using GYMWebApp.Models;
using System.Data;
using System.Data.Entity;

namespace GYMWebApp.Controllers
{
    public class AntremanController : BaseController
    {
        private WorkoutModel workoutmodel = new WorkoutModel();
        private Antreman _ant = new Antreman();
        private Sporcu _sp = new Sporcu();
        private HareketAltGrubu _haraltgrup = new HareketAltGrubu();
        private Antreman _silinecek;


        public ActionResult Index()
        {
     
            List<SelectListItem> sporcuant = new List<SelectListItem>();
            foreach (var item in db.Sporcu)
            {
                sporcuant.Add(new SelectListItem { Text = item.Adi+" "+item.Soyadi, Value = item.Id.ToString() });
            }

            ViewBag.Sporcular = sporcuant;
            return View(workoutmodel.ListtAll());
        }

        [HttpPost]
        public ActionResult Index(string Id)
        {
            List<SelectListItem> sporcuant = new List<SelectListItem>();
            foreach (var item in db.Sporcu)
            {                          
                    sporcuant.Add(new SelectListItem { Text = item.Adi + " " + item.Soyadi, Value = item.Id.ToString() });   
            }
            ViewBag.Sporcular = sporcuant;

            int Ids = Convert.ToInt32(Id);         
            var sporcuantreman = (from x in db.Antreman where x.Sporcu.Id == Ids select x).ToList();
            return View(sporcuantreman);
        }

        public ActionResult Create()
        {
            //AntremanModel model = getSporcu();
            List<SelectListItem> sporlis = new List<SelectListItem>();
            foreach (var item in db.Sporcu.ToList())
            {
                sporlis.Add(new SelectListItem { Text = item.Adi + "  " + item.Soyadi, Value = item.Id.ToString() });
            }

            ViewBag.SporcuListesi = sporlis;


            List<SelectListItem> _ant3 = new List<SelectListItem>();
            foreach (var item in db.HareketAltGrubu.ToList())
            {
                _ant3.Add(new SelectListItem { Text = item.HarAltGrupAdi, Value = item.Id.ToString() });

            }

            ViewBag.Antreman2 = _ant3;


            return View(_ant);
        }
        [HttpPost]
        public ActionResult Create(Antreman antreman, FormCollection _fc)
        {
            antreman.HarAltGrupId = antreman.Id;
            workoutmodel.Create(antreman);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Antreman antreman)
        {
            if (_silinecek!=null)
            {
                workoutmodel.DeleteIt(antreman);
            }
           
            return RedirectToAction("Index");
        }
        public ActionResult Update(int id = 0)
        {
            List<SelectListItem> _ant = new List<SelectListItem>();
            foreach (var item in db.Sporcu.ToList())
            {
                _ant.Add(new SelectListItem { Text = item.Adi, Value = item.Id.ToString() });
            }

            ViewBag.Antreman = _ant;


            List<SelectListItem> _ant2 = new List<SelectListItem>();
            foreach (var item in db.HareketAltGrubu.ToList())
            {
                _ant2.Add(new SelectListItem { Text = item.HarAltGrupAdi, Value = item.Id.ToString() });
            }

            ViewBag.Antreman2 = _ant2;
            return View(db.Antreman.Find(id));
        }

        [HttpPost]
        public ActionResult Update(Antreman antreman)
        {

            db.Entry(antreman).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //public AntremanModel getSporcu()
        //{
        //    AntremanModel _antlevent = new AntremanModel();
        //    _antlevent.SporcuListele = (from spo in db.Sporcu.ToList()
        //                                select new SelectListItem
        //                                {
        //                                    Selected = false,
        //                                    Text = spo.Adi,

        //                                    Value = spo.Id.ToString()
        //                                }).ToList();
        //    _antlevent.SporcuListele.Insert(0, new SelectListItem
        //    {
        //        Selected = true,
        //        Value = "",
        //        Text = "Seçiniz"
        //    });
        //    return getSporcu();
        //}
    }
}

GYMWebApp/Views/Antreman/Create.cshtml
@model GYMWebApp.DAL.Antreman

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Antreman</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SporcuId, "Sporcu Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SporcuId", new SelectList(ViewBag.SporcuListesi, "Value", "Text"), "Sporcu Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SporcuId, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.HarAltGrupId, "Hareket Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id", new SelectList(ViewBag.Antreman2, "Value", "Text"), "Hareket Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HarAltGrupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

GYMWebApp/Views/Antreman/Delete.cshtml
@model GYMWebApp.DAL.Antreman

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Sil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Antreman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HareketAltGrubu.HarAltGrupAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HareketAltGrubu.HarAltGrupAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sporcu.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sporcu.Adi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }
</div>

GYMWebApp/Views/Antreman/Index.cshtml
@model IEnumerable<GYMWebApp.DAL.Antreman>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main.cshtml";
}




<p>
    @using (Html.BeginForm("Index", "Antreman", FormMethod.Post))
    {
        <table>
            <tr>
                <th>
                    <h3>@Html.ActionLink("Yeni Antreman", "Create")</h3>
                </th>
                <th>
                    @Html.DropDownList("Id", new SelectList(ViewBag.Sporcular, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                </th>
                <th> <input type="submit" value="Ara" /></th>
    </tr>
    </table>
    }

    </p>
    <table class="table">
        <tr>
            <th>
                ADI

            </th>
            <th>
                SOYADI

            </th>
            <th>
                HAREKET ADI
            </th>

            <th> İŞLEMLER</th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sporcu.Adi)

                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.Sporcu.Soyadi)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.HareketAltGrubu.HarAltGrupAdi)
                </td>

                <td>

                    <button type="button" class="btn btn-default">@Html.ActionLink("Düzenle", "Update", new { id = item.Id }) </button>
                    <button type="button" class="btn btn-flat">@Html.ActionLink("Sil", "Delete", new { id = item.Id }) </button>
                </td>

            </tr>

        }

    </table>

GYMWebApp/Views/Antreman/Update.cshtml
@model GYMWebApp.DAL.Antreman

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Main.cshtml";
}

<h2>Güncelle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Antreman</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SporcuId, "Sporcu Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SporcuId", new SelectList(ViewBag.Antreman, "Value", "Text"), "Sporcu Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SporcuId, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.HarAltGrupId, "Hareket Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HarAltGrupId", new SelectList(ViewBag.Antreman2, "Value", "Text"), "Hareket Seçiniz", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HarAltGrupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>